### ISSUE TITLE
Autoscroll

### ISSUE THREAD

**Issue by sash85** [Shopify/dashing#567] opened 2015-05-20 16:13 UTC
Hi,

is it possible to automatic scroll in a single widget? 
I have a spreadsheet which is sometimes longer and it should scroll down to the bottom and then back to the top.
I can scroll the whole site with jquery but it doesn't work in a single widget.
I use this kind of code.

Edit: my complete code

    <script type='text/javascript'>
    setTimeout(function() { scroll_down(); }, 5000);
    
    function scroll_down() {
      $('li.Scroll').animate({
          scrollTop: $("#vplan_content").height() - $(window).height() + 50
      },30000);
      setTimeout(function() { scroll_up(); }, 40000);
    }
    function scroll_up() {
      $('li.Scroll').animate({
        scrollTop: 0
      },30000);
      setTimeout(function() { scroll_down(); }, 40000);
    }
    </script>

**Comment by howardsternisbatman** [comment] 2015-05-20 19:10
Hi, I'm sorry I can't help here but I am interested to know which widget you are using to display a spreadsheet.

thanks

**Comment by tylermauthe** [comment] 2015-05-20 23:27
If `#div-id` in that context refers to the div you want to scroll, the code you have written should work.

Here is a simple CodePen which demonstrates the behaviour in simplified form:
http://codepen.io/tylermauthe/pen/xGEEXE

This isn't specifically a problem with Dashing, please close this issue and ask the question on StackOverflow or similar. This is almost certainly caused by your CSS rules.

**Comment by sash85** [comment] 2015-05-21 07:47
@howardsternisbatman: i'm not a good coder thats why a friend help me to embed the google API. I will ask him to publish the widget asap. 

@tylermauthe: Thank you! I change my first post and paste my complete (not working) code in. I will try your solution.

**Comment by sash85** [comment] 2015-05-21 08:35
It works! :-).

It was a simple bug in css. Thanks for your quick help!

@howardsternisbatman: @mtempel will post the widget in the next days.

**Comment by howardsternisbatman** [comment] 2015-05-21 17:49
@sash85 thanks! Please post a link here.

:-)

**Comment by pushmatrix** [comment] 2015-05-25 13:43
Closing this for now. But please share when you're done :)

**Closed by pushmatrix** 2015-05-25 13:43 UTC

**Comment by sash85** [comment] 2015-05-27 12:40
so here it is :-) 
https://github.com/mtempel/spreadsheetDemo

**Comment by mtempel** [comment] 2015-05-27 13:06
here is the code to get spreadsheets into dashing https://github.com/mtempel/spreadsheetDemo
