### ISSUE TITLE
Alternative for batman.js?

### ISSUE THREAD

**Issue by newcron** [Shopify/dashing#592] opened 2015-07-06 14:39 UTC
Hi Guys, 
as batman.js has been declared dead on it's [homepage](http://batmanjs.org/) did you consider providing an alternative to it? Frankly, for most cases, batman just goes lightyears beyond what would be necessary.... 

Maybe adding mustache as alternative view technology (also renderable from javascript) would be an interesting alternative? It provides only a 1/1000th of batmans features, but should perfectly do the 80/20

**Comment by r0n22** [comment] 2015-07-06 15:47
Duplicate of #498.

**Closed** 2015-07-06 15:50 UTC
