### ISSUE TITLE
Future of Batmanjs

### ISSUE THREAD

**Issue by newcron** [Shopify/dashing#584] opened 2015-06-23 12:28 UTC
Hi Guys, 
Given that batman.js was abandoned - are there any alternatives planned for views in dashing? 
Although a bit different in architecture, mustache.js could work out just fine.

**Comment by tylermauthe** [comment] 2015-06-23 17:59
Duplicate of #498.

mustache.js is not an adequate substitute for batman.

**Comment by tylermauthe** [comment] 2015-07-07 05:34
Duplicate of #592 ... :trollface:

**Comment by thelinuxlich** [comment] 2015-07-08 06:01
I took a stab on this but using Node.js and Vue: https://github.com/thelinuxlich/vue-dashing-js

**Comment by Guillaumichaud** [comment] 2015-12-18 09:53
Why not closing this issue as it is a duplicate of #498?

**Closed** 2015-12-18 15:26 UTC
